name: Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...

      - name: Benchmark
        run: go test -run=^$ -bench=BenchmarkReference -benchmem

      #- name: Coverage
      #  run: ./s/test_with_codecoverage.sh

      - name: Staticcheck
        run: |
          go get -u honnef.co/go/tools/cmd/staticcheck
          # TODO: fix issues and re-enable
          # staticcheck ./...
